directories:
  output: build
  buildResources: build
publish:
  - provider: generic
    url: 'https://github.com/MarlonYJG/workSpace/tree/master/odin'
appId: Odin.Browser
win:
  icon: public\img\tray\app.ico
  artifactName: '${productName}_setup_${version}.${ext}'
  target:
    - nsis
asar: true
nsis:
  oneClick: false
  menuCategory: Odin-ABC
  shortcutName: Odin-ABC
  allowToChangeInstallationDirectory: true
  perMachine: true
  runAfterFinish: true
mac:
  icon: public\img\tray\app.icns
  category: browers
  target:
    - dmg
dmg:
  window:
    x: 100
    'y': 100
    width: 500
    height: 300
electronVersion: 2.0.7
